http:
  host: 'localhost'
  port: 8082

database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'admin'
  database: 'class_assist'

auth:
  expireIn: '60s'
  secret: 'This is a very secret string'
