http:
  host: 'localhost'
  port: 8082

database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'class_assist'

auth:
  accessTokenExpire: '5s'
  refreshTokenExpire: '60s'
  secret: 'This is a very secret string'
